### ISSUE TITLE
User password sent back from the endpoint

### ISSUE THREAD

**Issue by nicolashmln** [VirtusLab/strapi-plugin-comments#12]
Hi,

Since the beta 5 I can see the hashed password of the user in the response of the API. In my example I used the `/comments/:relation` endpoint.

<img width="355" alt="Capture d’écran 2020-11-19 à 21 14 33" src="https://user-images.githubusercontent.com/22435892/99719682-f0586b00-2aac-11eb-9d32-7552377b16df.png">

I think it might be a security problem.

I guess it's because of all the `sanitizeEntity` have been removed ?

**Comment by cyp3rius** [comment]
Thanks for flagging this @nicolashmln. We will take that asap.

**Comment by cyp3rius** [comment]
@nicolashmln `beta-6` has been released. Sanitization has been reverted and limited only to the `authorUser` relation.
