### ISSUE TITLE
InternalServerError: Cast to ObjectId failed for value "5" at path "_id" for model "comment"

### ISSUE THREAD

**Issue by cyp3rius** [VirtusLab/strapi-plugin-comments#15]
Having a somewhat related issue. I get the following error message when I go to "Plugins" -> "Comments" -> Comment I just posted.

``error InternalServerError: Cast to ObjectId failed for value "5" at path "_id" for model "comment"``

<img width="1446" alt="Screen Shot 2020-12-05 at 11 28 13 AM" src="https://user-images.githubusercontent.com/2127545/101255567-070fea80-375a-11eb-96b9-65fb0e663a97.png">

This is what I POST to create a new comment (not sure maybe thats where the issue is?)

```
{
    "authorUser": "5fb48e746b458f4dc1da0751",
	"content": "My sample response",
	"related": [{
		"refId": "5fcba9fee5e1787e022cf178",
		"ref": "post",
		"field": "comments"
	}]
}
```
refId is the ID of the post I am trying to comment on. Same ID is being supplied via the endpoint: 

``POST http://localhost:1337/comments/post:5fcba9fee5e1787e022cf178`` (not sure if it needs to be supplied in both places: URL and the body of the request)

When I go to that post I can definitely see that the new comment was "propagated":

<img width="344" alt="Screen Shot 2020-12-05 at 11 35 19 AM" src="https://user-images.githubusercontent.com/2127545/101258074-f14ef500-375a-11eb-9091-9535d104abaa.png">

Any ideas?

_Originally posted by @mikekoro in https://github.com/VirtusLab/strapi-plugin-comments/issues/14#issuecomment-739318264_

**Comment by cyp3rius** [comment]
@mikekoro @ibnumubarok what version of Strapi and plugin are you using? May I ask for the full stack trace?

**Comment by ibnumubarok** [comment]
Thanks for opening a new issue @cyp3rius 

I'm using the latest version, for both Strapi (3.3.4) & plugin (1.0.0-beta.6).

After trying to do another look on this, I found that this issue related with MongoDB datatype. If I setup Strapi using SQLite, the plugin works well, but error when I use MongoDB.

ID of an entry on MongoDB is an ObjectID, while on other db, it's an integer. This cause the error.

>[2020-12-07T12:09:02.029Z] error InternalServerError: Cast to ObjectId failed for value "5" at path "_id" for model "comment"
>    at Object.throw (/Users/ibnu/work/temp/strapi-comment/node_modules/koa/lib/context.js:97:11)
>    at throwError (/Users/ibnu/work/temp/strapi-comment/node_modules/strapi-plugin-comments/controllers/comments.js:18:41)
>    at Object.findOne (/Users/ibnu/work/temp/strapi-comment/node_modules/strapi-plugin-comments/controllers/comments.js:119:7)
>    at runMicrotasks (<anonymous>)
>    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by cyp3rius** [comment]
Thanks for highlighting that @ibnumubarok. I will prepare the fix in couple of hours.

**Comment by cyp3rius** [comment]
@ibnumubarok @mikekoro version `beta-7` has been published with the uuid fix. Close the ticket once it helps.

**Comment by cyp3rius** [comment]
Closing. In case of need raise a new ticket please.
