### ISSUE TITLE
API accepts any existing user for "authorUser" field

### ISSUE THREAD

**Issue by Mo9a7i** [VirtusLab/strapi-plugin-comments#18]
Currently, any API caller can put any user ID in the "authorUser" field, which means, people can comment in place of each other.
Neither the authorId nor the Created By fields have information about the original submitter of the comment based on authentication token.

**Comment by cyp3rius** [comment]
@Mo9a7i so if I understood you correctly while making a PUT request you're able to change the authorUser field value. That was your observation?

**Comment by cyp3rius** [comment]
@Mo9a7i I've made a test.

Got 2 users with ids `1` and `2`.

1. Create comment for user with id `1`
2. Try to update the comment using id `2` -> Results as 409. Expected
3. Try to update the comment using id `1` -> Results as 200. Expected.

See the attachments. 

Can you please describe in more details what was the case?

**Important note.** If you're using default Strapi Content Manager endpoints we're not responsible for their behavior and changes made there. Usage of plugin endpoints described in the `Readme.md` is only supported and is going to be investigated.

![Zrzut ekranu 2020-12-9 o 09 04 15](https://user-images.githubusercontent.com/11504214/101601922-91c44400-39fd-11eb-94c6-303fb85bb6d9.png)
![Zrzut ekranu 2020-12-9 o 09 00 28](https://user-images.githubusercontent.com/11504214/101601946-9db00600-39fd-11eb-994d-275558eb46e2.png)

**Comment by Mo9a7i** [comment]
Hello Boss,

The issue is with the original Post call

see screenshot below, the jwt token is for user 1250

I can submit with authorUser 505 for example

![image](https://user-images.githubusercontent.com/1753262/101620490-f3190100-3a57-11eb-84b7-edb4ab888d24.png)


    "strapi": "3.3.4",
    "strapi-plugin-comments": "^1.0.0-beta.6",

**Comment by cyp3rius** [comment]
Plugin is prepared to work with both, Strapi & non-Strapi users. That's why you're controlling explicit which user have to be assigned to the comment. It is not checking the jwt of logger user to not be strict with Strapi users only.

**Comment by Mo9a7i** [comment]
I have built a small hack, based on documentation and online solutions for the problem, have a look and if its good, just take it.

**Comment by cyp3rius** [comment]
You would be welcome to contribute to the plugin also :)

**Comment by Mo9a7i** [comment]
```javascript

async create(ctx) {
      let entity;
      let user = {};
      if (!ctx.state.user) { user.id = 88; } // here I have registered user called "Anonymous" that has id 88, so any unauthenticated request I give it user id 88, for complete anonymous, you can just move the if statement to the below if statement, and not add an author object to the data if there was no author.
      else { user = ctx.state.user; }

      if (ctx.is('multipart')) {
        const { data, files } = parseMultipartData(ctx);
        data.author = user.id;
        entity = await strapi.services.jokes.create(data, { files });
      } 
      else {
        ctx.request.body.author = user.id;
        entity = await strapi.services.jokes.create(ctx.request.body);
      }

      return sanitizeEntity(entity, { model: strapi.models.jokes });
    },

```

**Comment by Mo9a7i** [comment]
> You would be welcome to contribute to the plugin also :)

it would be an honor, I'm just trying to figure out your way of coding, so I can contribute the way that suites you.

**Comment by cyp3rius** [comment]
Closing in relation to the raised feature request for `v1.1.1`.
