### ISSUE TITLE
Split out Reporting and Liking functionality

### ISSUE THREAD

**Issue by Mo9a7i** [VirtusLab/strapi-plugin-comments#20]
I stumbled upon this plugin since i had the need for comments functionality into my project, instead of building a new one, I saw this to be fit and had many of the functionalities i needed built in, such as, I can added to any content type.

However, another functionality I needed in my application is thumbs up thumbs down or (like dislike) or voting. I can see it exists in this plugin and it looks like a waste that I can only use it with comments, and have to rebuild the whole thing for other content types.

my recommendation is, to remove this functionality out of this plugin purpose, and build to separate plugins or one plugin for liking disliking and reporting abuse

so the admin panel would see latest reports, and resolutions, also, the votes up votes down function can be seen from any content page, or part of any content type response.

Not sure if it fits your vision and strategy and if such issues are acceptable to be reported here

**Comment by cyp3rius** [comment]
Hi @Mo9a7i, what you're writing it's quite reasonable when you're looking to the wider context but it becomes quite big functionality at all :) At some point in the future it the plan is to transform this plugin to the Community Engagement tool, that will deliver:

- Comments
- Reports (to comments and other Content Types)
- Scoring (to comments and other Content Types)
- Notifications
- Automated moderation
- Socials sharing / integration
- Import / Export (from WP for example)

But that's a bit far future :) For now I think you've to manage it by your own forces and built-in Strapi APIs

**Comment by Mo9a7i** [comment]
Didnt know that 😉 
I agree if it was planned to be an engagement tool, that is awesome.

**Comment by cyp3rius** [comment]
Yep, that's the long term plan. Early 2021 together with VirtusLab RnD team we will publish our roadmap for all the plugins (including this one).
