### ISSUE TITLE
Support default Strapi parameters by querying data

### ISSUE THREAD

**Issue by kwiat1990** [VirtusLab/strapi-plugin-comments#25]
Hi,

By default Strapi custom endpoints have the possibility to pass in some parameters in order to filter or sort data. See: https://strapi.io/documentation/developer-docs/latest/content-api/parameters.html. 

It seems like comments plugin doesn't support any kind of parameters, so there is no other way than to write custom code in a controller (by default there is no controller file, so is it even possible?). I think it would be something worth considering. For now I can think of two use cases, where I would like to limit my query somehow: 
* pagination (user loads initially only X newest comments, older comments should be fetch only if the user want them to see)
* counting (check if some components are needed or some requests have to be made).

**Comment by Mo9a7i** [comment]
agree i think it relates to #21

**Comment by cyp3rius** [comment]
@Mo9a7i @kwiat1990  change introduced in `v1.0.1-beta.4`. After testing please close the ticket.

**Comment by kwiat1990** [comment]
All available parameters seems to work seamlessly. I have tested those described in examples on Strapi's documentation page. 

One problem though. If a request to the default endpoint (`comments/<relation>:<id>`) get parameterized then the nested comments from `children` field will be ignored and not attached to the response. For me it is rather unwanted behavior. For the very same result another endpoint  (`comments/<relation>:<id>/flat`) could be used.

Response for `comments/<relation>:<id>` with parameter `?id=1` (for brevity I have removed all irrelevant and nullish fields):
```
[
  {
    "id": 1,
    "content": "lorem ipsum",
    "authorUser": {
      "id": 1,
      "username": "lorem",
      "email": "lorem@ipsum.com",
    },
    "children": []
  }
```
vs without parameters:
```
[
  {
    "id": 1,
    "content": "lorem ipsum",
    "authorUser": {
      "id": 1,
      "username": "lorem",
      "email": "lorem@ipsum.com",
    },
    "children": [
      {
        "id": 2,
        "content": "lorem ipsum",
        "authorId": "lorem2@ipsum.com",
        "authorEmail": "lorem2@ipsum.com",
        "relatedSlug": "article:1",
        "children": []
      }
    ]
  }
```

I would except that the response structure won't be influenced by parameters, so if some comment has nested comments, then they should be attached to the response object as they would in standard request without parameters.

@cyp3rius please decide how we deal with it further.

**Comment by cyp3rius** [comment]
Provided expected behavior in `1.0.1-beta.5`

**Comment by kwiat1990** [comment]
Bingo, I have tested it and it works like a charm. All nested comments are attached to the response. Thanks!

**Comment by kwiat1990** [comment]
@cyp3rius , it has turned out that not all the parameters work as intended. Fetching comments by id or with a `limit` param works and the comments will be return including its children. But as soon as `sort` parameter will be used, all nested comment will be ignored.

`http://localhost:1337/comments/article:1?_sort=created_at:desc` doesn't work.
