### ISSUE TITLE
No Sorting, Accept any value for email

### ISSUE THREAD

**Issue by Mo9a7i** [VirtusLab/strapi-plugin-comments#29]
- cannot sort comments by calling `/comments/content-type:id?_sort=id:desc`
- the plugin has no validation for email for unauthenticated users

**Comment by cyp3rius** [comment]
@Mo9a7i under investigation.

**Comment by cyp3rius** [comment]
@Mo9a7i change introduced in `v1.0.1-beta.4`. After testing please close the ticket.

**Comment by cyp3rius** [comment]
Closing as already tested in #25
