### ISSUE TITLE
Bad words filter is too sensitive. Make it optional

### ISSUE THREAD

**Issue by kwiat1990** [VirtusLab/strapi-plugin-comments#31]
Hi,

as I was testing my comments I saw that the bad word filter seems to be way too strong. It blocks comments containing some normal words like "hell". 

I think it's somehow weid that a comment containing "hell" get blocked and all I can do is to display an error like: `Bad language used! Please polite your comment...\",\"content\":{\"original\":\"hell\`. It's pretty thin line what' good and what's no. This automatic filter could be a super way to handle very abusive comments but I thinks it is rarely the case and it is better to moderate comments by hand after they got posted. I would love to have an option to disable the bad-word filter and manage the comments myself. I think I would be better doing so than automatically blocking legit comments. It might be also a case that having comments with bad words isn't necessarily a bad thing. It would say it depends on the context and your audience.

**Comment by kwiat1990** [comment]
Yeah, it sounds reasonably to make it that way. The only thing I don't know quite well is how complicated and time consuming this would be, so I would suggest to split the task.

Optional deactivation of the filter seems from my perspective easier to implement and perhaps could be a factor for more people, while the second one is rather nice to have. Although it could be possibly a thing for new user considering if they should use this plugin.

**Comment by cyp3rius** [comment]
Agreed. ETA is Monday / Tuesday.

**Comment by cyp3rius** [comment]
@kwiat1990 version `1.0.1-beta.3` contains what you expect. Refer to the updated Readme.md please.

**Comment by kwiat1990** [comment]
Cool, later in the week I should be able to test it. Thanks a lot these fast adjustment!

**Comment by cyp3rius** [comment]
Sure, once it will be satisfying please close the ticket.

**Comment by kwiat1990** [comment]
The new flag for enabling/disabling bad words filter does what it should. I have tested it and it works perfectly fine in both cases.
