### ISSUE TITLE
threadOf does not work with MongoDB

### ISSUE THREAD

**Issue by johnnietirado** [VirtusLab/strapi-plugin-comments#40]
`buildNestedStructure` uses a `===` check for the id of the thread but in MongoDB relationship fields are saved as **ObjectId** so the equality if doing a reference check.

```
const buildNestedStructure = (entities, id = null, field = 'parent', dropBlockedThreads = false, blockNestedThreads = false) =>
    entities
        .filter(entity => (entity[field] === id) || (isObject(entity[field]) && (entity[field].id === id)))
        .map(entity => ({ 
            ...entity, 
            [field]: undefined, 
            related: undefined,
            blockedThread: blockNestedThreads || entity.blockedThread,
            children: entity.blockedThread && dropBlockedThreads ? [] : buildNestedStructure(entities, entity.id, field, dropBlockedThreads, entity.blockedThread),
        }));
```

### Workaround

Extend model inside of your own project and change `threadOf` attribute to following:

```
"threadOf": {
      "columnName": "threadOf",
      "type": "text",
      "configurable": false
    },
```

This way the comparison will work as expected.

P.S. Awesome plugin, saved me from creating my own implementation 🤘

**Comment by cyp3rius** [comment]
@johnnietirado, we've verified the case with mongo and indeed there is an issue. @Kronos66  is taking care of it as part of #41 PR.

**Comment by Sheey11** [comment]
This change also affect `findOneAndThread` in `services/comment.js`:
```javascript
return {
    selected: {
        ...selectedEntity,
        threadOf: selectedEntity.threadOf ? filterOurResolvedReports(selectedEntity.threadOf) : null,
    },
    level: entitiesOnSameLevel.map(_ => filterOurResolvedReports(_))
};
```
`filterOurResolvedReports(selectedEntity.threadOf)` recongize the param as a `Comment` object, but after modifing it will be `id` of the comment, so it must replaced as
```javascript
return {
    selected: {
        ...selectedEntity,
        threadOf: selectedEntity.threadOf ? filterOurResolvedReports(strapi.query(model.modelName, pluginName).findOne({ id: selectedEntity.threadOf})) : null,
    },
    level: entitiesOnSameLevel.map(_ => filterOurResolvedReports(_))
};
```
This will fix the error on viewing the thread on admin panel.

**Comment by cyp3rius** [comment]
Yep @Sheey11, the mongo issue is wider than expected. But seems we've got a fix for that, keep you posted.

**Comment by DennieMello** [comment]
There is such an error on postgres too..
![Снимок_экрана_2021-03-08_в_17_31_54](https://user-images.githubusercontent.com/39631512/110334934-58b76200-8034-11eb-9f44-f0157cfdb178.jpg)

**Comment by cyp3rius** [comment]
@Sheey11 fixed already in the most recent version.
